name: Check Site Every 4 Hours

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install --with-deps

      - name: Run script
        run: python script.py
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
